type: object
required:
  - id
  - label
properties:
  id:
    type: string
    format: uuid
    readOnly: true
  dateCreated:
    type: string
    format: date-time
    readOnly: true
  lastUpdated:
    type: string
    format: date-time
    readOnly: true
  label:
    type: string
  name:
    type: string
  description:
    type: string
  weight:
    type: integer
    default: 0