type: object
required:
  - id
properties:
  id:
    type: string
    format: uuid
    readOnly: true
  dateCreated:
    type: string
    format: date-time
    readOnly: true
  lastUpdated:
    type: string
    format: date-time
    readOnly: true
  note:
    type: string
