allOf:
  - $ref: ../../common/schemas/RemoteOkapiLink.yaml
  - type: object
    required:
      - owner
    properties:
      owner:
        type: object
        readOnly: true
        required:
          - id
        properties:
          id:
            type: string
            format: uuid
