type: object
properties:
  message:
    type: string
  path:
    type: string
  _links:
    type: object
    properties:
      self:
        type: object
        properties:
          href:
            type: string
            format: uri
