type: object
required:
  - message
  - path
  - _links
properties:
  message:
    type: string
  path:
    type: string
  _links:
    type: object
    required:
      - self
    properties:
      self:
        type: object
        required:
          - href
        properties:
          href:
            type: string
            format: uri
