parameters:
  - $ref: ../common/parameters/x-okapi-tenant.yaml
  - $ref: ../components/parameters/partyId.yaml
get:
  tags:
    - Parties
  summary: Get a specified party record
  operationId: getParty
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Party.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/HttpError.yaml
    '500':
      description: Internal server error
put:
  tags:
    - Parties
  summary: Update party record
  operationId: putParty
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Party.yaml
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Party.yaml
    '400':
      description: Bad request error
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/HttpError.yaml
    '500':
      description: Internal server error
delete:
  tags:
    - Parties
  summary: Delete a specified party record
  operationId: deleteParty
  responses:
    '204':
      description: No content
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/HttpError.yaml
    '500':
      description: Internal server error
