description: Supports search and creation of parties.
parameters:
  - $ref: ../common/parameters/x-okapi-tenant.yaml
get:
  tags:
    - Parties
  summary: Get a set of party records.
  operationId: getParties
  parameters:
    $ref: ../common/parameters/queryParameters.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            oneOf:
              - $ref: ../components/schemas/PartyResults.yaml
              - $ref: ../components/schemas/PartyResultsArray.yaml
    '400':
      description: Bad request error
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
    '500':
      description: Internal server error
post:
  tags:
    - Parties
  summary: Create party record
  operationId: postParty
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Party.yaml
    required: true
  responses:
    '201':
      description: Created
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Party.yaml
    '400':
      description: Bad request error
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
    '422':
      description: Validation error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/ValidationErrorResponse.yaml
    '500':
      description: Internal server error
