parameters:
  - $ref: ../common/parameters/x-okapi-tenant.yaml
  - $ref: ../components/parameters/titleInstanceId.yaml
get:
  tags:
    - Title instances
  summary: Get a specified title instance record
  operationId: getTitleInstance
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/TitleInstance.yaml
    '400':
      description: Bad request error
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/SpringBootErrorResponse.yaml
    '500':
      description: Internal server error
