parameters:
  - $ref: ../common/parameters/x-okapi-tenant.yaml
  - $ref: ../components/parameters/workId.yaml
get:
  tags:
    - Works
  summary: Get a specified work record
  operationId: getWork
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Work.yaml
    '400':
      description: Bad request error
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/SpringBootErrorResponse.yaml
    '500':
      description: Internal server error
put:
  tags:
    - Works
  summary: Update work record
  operationId: putWork
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Work.yaml
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Work.yaml
    '400':
      description: Bad request error
    '401':
      description: Unauthorized
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/SpringBootErrorResponse.yaml
    '422':
      description: Validation error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/ValidationErrorResponse.yaml
    '500':
      description: Internal server error
